Repository prgrms-web-devcourse-final-project/WEB1_1_DDang_BE, pull requests merged in 2024-12, with the labels that each got.

#57 [Feat/#47] dog crud extend logic
  src/main/java/team9/ddang/dog/controller/DogController.java
  src/main/java/team9/ddang/dog/controller/request/CreateDogRequest.java
  src/main/java/team9/ddang/dog/controller/request/UpdateDogRequest.java
  src/main/java/team9/ddang/dog/entity/Dog.java
  src/main/java/team9/ddang/dog/exception/DogExceptionMessage.java
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/dog/service/DogService.java
  src/main/java/team9/ddang/dog/service/request/CreateDogServiceRequest.java
  src/main/java/team9/ddang/dog/service/request/UpdateDogServiceRequest.java
  src/main/java/team9/ddang/dog/service/response/CreateDogResponse.java
  src/main/java/team9/ddang/dog/service/response/GetDogResponse.java
  src/main/java/team9/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/team9/ddang/global/config/websocket/WebSocketConfig.java
  src/main/java/team9/ddang/member/service/response/FriendResponse.java
  src/main/java/team9/ddang/walk/util/WalkCalculator.java
Labels: ✨Feature, 노관태

#60 [feat : #59] gitHub Action CD 추가
  .github/workflows/gradle.yml
Labels: ✨Feature, 문재경

#63 [Fix/#61] GitHub action fix
  .github/workflows/gradle.yml
  docker-compose.yml
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/global/config/security/CorsConfig.java
  src/main/java/team9/ddang/global/config/websocket/WebSocketConfig.java
Labels: 🔥BugFix, 문재경

#67 [fix:#66] 모든 경로 cors 설정 적용
  src/main/java/team9/ddang/global/config/security/CorsConfig.java
  src/main/java/team9/ddang/global/config/websocket/WebSocketConfig.java
Labels: 🔥BugFix, 노관태

#69 fix: #68 OPTIONS 요청 무시
  src/main/java/team9/ddang/global/config/security/SecurityConfig.java
  src/main/java/team9/ddang/member/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: 🔥BugFix, 송경훈

#71 chore: #58 깃헙 액션 비활성화
  .github/workflows/gradle.yml
Labels: ⚙️Setting, 노관태

#73 [Fix/#72] websocket 오류 해결
  src/main/java/team9/ddang/global/config/security/SecurityConfig.java
  src/main/java/team9/ddang/global/config/websocket/StompHandler.java
  src/main/java/team9/ddang/global/config/websocket/WebSocketConfig.java
  src/main/java/team9/ddang/walk/controller/WalkLogController.java
  src/main/java/team9/ddang/walk/service/WalkLogService.java
  src/main/java/team9/ddang/walk/service/WalkLogServiceImpl.java
  src/test/java/team9/ddang/family/repository/WalkScheduleRepositoryTest.java
  src/test/java/team9/ddang/family/service/FamilyServiceImplTest.java
  src/test/java/team9/ddang/family/service/WalkScheduleServiceImplTest.java
  src/test/java/team9/ddang/member/controller/FriendControllerTest.java
  src/test/java/team9/ddang/member/controller/MemberControllerTest.java
Labels: 🔥BugFix, 문재경

#62 [Feat/#46] chat family add functionality
  src/main/java/team9/ddang/chat/controller/ChatRoomController.java
  src/main/java/team9/ddang/chat/repository/ChatRepository.java
  src/main/java/team9/ddang/chat/service/ChatRoomServiceImpl.java
  src/main/java/team9/ddang/chat/service/WebSocketMessageService.java
  src/main/java/team9/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/team9/ddang/family/service/WalkScheduleServiceImpl.java
  src/main/java/team9/ddang/global/config/websocket/StompHandler.java
  src/main/java/team9/ddang/global/controller/WebSocketController.java
  src/main/java/team9/ddang/global/controller/response/WebSocketChatInfoResponse.java
  src/main/java/team9/ddang/global/event/WebSocketMessageEvent.java
Labels: ✨Feature, 🔨Refactor, 노관태

#74 Feat#44 Notification 구현
  src/main/java/team9/ddang/DDangApplication.java
  src/main/java/team9/ddang/family/controller/request/WalkScheduleCreateRequest.java
  src/main/java/team9/ddang/family/entity/DayOfWeek.java
  src/main/java/team9/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/team9/ddang/global/config/security/SecurityConfig.java
  src/main/java/team9/ddang/member/service/FriendServiceImpl.java
  src/main/java/team9/ddang/member/service/MemberServiceImpl.java
  src/main/java/team9/ddang/member/service/response/MyPageResponse.java
  src/main/java/team9/ddang/notification/controller/NotificationController.java
  src/main/java/team9/ddang/notification/controller/NotificationSettingsController.java
  src/main/java/team9/ddang/notification/controller/request/NotificationSettingsRequest.java
  src/main/java/team9/ddang/notification/entity/Notification.java
  src/main/java/team9/ddang/notification/entity/NotificationSettings.java
  src/main/java/team9/ddang/notification/entity/Type.java
  src/main/java/team9/ddang/notification/exception/NotificationExceptionMessage.java
  src/main/java/team9/ddang/notification/repository/NotificationRepository.java
  src/main/java/team9/ddang/notification/repository/NotificationSettingsRepository.java
  src/main/java/team9/ddang/notification/scheduler/NotificationDeleteScheduler.java
  src/main/java/team9/ddang/notification/scheduler/WalkScheduleNotificationScheduler.java
  src/main/java/team9/ddang/notification/scheduler/request/FamilyRoleMessageRequest.java
  src/main/java/team9/ddang/notification/scheduler/request/NotificationSchedulerRequest.java
  src/main/java/team9/ddang/notification/service/NotificationService.java
  src/main/java/team9/ddang/notification/service/NotificationServiceImpl.java
  src/main/java/team9/ddang/notification/service/NotificationSettingsService.java
  src/main/java/team9/ddang/notification/service/NotificationSettingsServiceImpl.java
  src/main/java/team9/ddang/notification/service/request/FriendNotificationRequest.java
  src/main/java/team9/ddang/notification/service/response/NotificationResponse.java
  src/main/java/team9/ddang/notification/service/response/SettingsResponse.java
  src/main/java/team9/ddang/notification/service/response/SettingsUpdateResponse.java
  src/test/java/team9/ddang/member/controller/MemberControllerTest.java
Labels: ✨Feature, 송경훈

#76 [Feat/#64] family chat api mod
  src/main/java/team9/ddang/chat/controller/ChatController.java
  src/main/java/team9/ddang/chat/repository/ChatRepository.java
  src/main/java/team9/ddang/chat/service/ChatRoomServiceImpl.java
  src/main/java/team9/ddang/chat/service/ChatService.java
  src/main/java/team9/ddang/chat/service/ChatServiceImpl.java
  src/main/java/team9/ddang/chat/service/response/ChatMemberInfo.java
  src/main/java/team9/ddang/chat/service/response/ChatRoomResponse.java
  src/main/java/team9/ddang/dog/repository/DogRepository.java
  src/main/java/team9/ddang/family/controller/FamilyController.java
  src/main/java/team9/ddang/family/controller/WalkScheduleController.java
  src/main/java/team9/ddang/family/controller/request/WalkScheduleCreateRequest.java
  src/main/java/team9/ddang/family/controller/request/WalkScheduleDeleteRequest.java
  src/main/java/team9/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/team9/ddang/family/service/FamilyService.java
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/family/service/WalkScheduleService.java
  src/main/java/team9/ddang/family/service/WalkScheduleServiceImpl.java
  src/main/java/team9/ddang/family/service/request/WalkScheduleCreateServiceRequest.java
  src/main/java/team9/ddang/family/service/request/WalkScheduleDeleteServiceRequest.java
  src/main/java/team9/ddang/family/service/response/FamilyDetailResponse.java
  src/main/java/team9/ddang/family/service/response/FamilyResponse.java
  src/main/java/team9/ddang/family/service/response/MemberInfo.java
  src/main/java/team9/ddang/family/service/response/WalkScheduleInfo.java
  src/main/java/team9/ddang/walk/repository/WalkRepository.java
  src/test/java/team9/ddang/family/service/FamilyServiceImplTest.java
  src/test/java/team9/ddang/family/service/WalkScheduleServiceImplTest.java
Labels: ✨Feature, 노관태

#79 [Feat/#70] s3 service
  build.gradle
  src/main/java/team9/ddang/dog/controller/DogController.java
  src/main/java/team9/ddang/dog/controller/request/CreateDogRequest.java
  src/main/java/team9/ddang/dog/controller/request/UpdateDogRequest.java
  src/main/java/team9/ddang/dog/service/DogService.java
  src/main/java/team9/ddang/dog/service/request/CreateDogServiceRequest.java
  src/main/java/team9/ddang/dog/service/request/UpdateDogServiceRequest.java
  src/main/java/team9/ddang/global/config/S3Config.java
  src/main/java/team9/ddang/global/service/S3Service.java
  src/main/java/team9/ddang/member/service/response/FriendListResponse.java
  src/main/java/team9/ddang/walk/repository/WalkDogRepository.java
  src/main/java/team9/ddang/walk/repository/WalkRepository.java
  src/main/java/team9/ddang/walk/service/WalkLogServiceImpl.java
  src/main/java/team9/ddang/walk/service/response/log/WalkLogResponse.java
Labels: ✨Feature, 문재경

#82 [Refactor/#80] 친구, 산책 응답 및 간단한 로직 변경
  docker-compose.yml
  src/main/java/team9/ddang/dog/controller/DogController.java
  src/main/java/team9/ddang/global/controller/WebSocketWalkController.java
  src/main/java/team9/ddang/member/controller/FriendController.java
  src/main/java/team9/ddang/member/controller/request/AddFriendRequest.java
  src/main/java/team9/ddang/member/repository/FriendRequestRepository.java
  src/main/java/team9/ddang/member/service/FriendService.java
  src/main/java/team9/ddang/member/service/FriendServiceImpl.java
  src/main/java/team9/ddang/member/service/response/MainResponse.java
  src/main/java/team9/ddang/walk/controller/WalkController.java
  src/main/java/team9/ddang/walk/service/WalkLocationServiceImpl.java
  src/main/java/team9/ddang/walk/service/WalkLogServiceImpl.java
  src/main/java/team9/ddang/walk/service/WalkService.java
  src/main/java/team9/ddang/walk/service/WalkServiceImpl.java
  src/main/java/team9/ddang/walk/service/request/walk/CompleteWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/response/log/WalkLogByFamilyResponse.java
  src/main/java/team9/ddang/walk/service/response/log/WalkLogResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/CompleteWalkResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/DecisionWalkResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/MemberNearbyResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/ProposalWalkResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/Type.java
  src/main/java/team9/ddang/walk/service/response/walk/WalkWithResponse.java
  src/test/java/team9/ddang/member/controller/FriendControllerTest.java
Labels: 🔨Refactor, 문재경

#87 fix: #81 WalkWithMember BaseEntity 적용
  src/main/java/team9/ddang/member/entity/WalkWithMember.java
  src/main/java/team9/ddang/member/repository/WalkWithMemberRepository.java
Labels: 🔥BugFix, 송경훈

#83 [Feat/#78] chat family walk schedule refactor
  build.gradle
  src/main/java/team9/ddang/chat/exception/ChatExceptionMessage.java
  src/main/java/team9/ddang/chat/repository/ChatMemberRepository.java
  src/main/java/team9/ddang/chat/repository/ChatRepository.java
  src/main/java/team9/ddang/chat/repository/ChatRoomRepository.java
  src/main/java/team9/ddang/chat/service/ChatRoomServiceImpl.java
  src/main/java/team9/ddang/chat/service/ChatServiceImpl.java
  src/main/java/team9/ddang/dog/service/DogService.java
  src/main/java/team9/ddang/family/repository/FamilyRepository.java
  src/main/java/team9/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/family/service/WalkScheduleServiceImpl.java
  src/test/java/team9/ddang/chat/repository/ChatRepositoryTest.java
  src/test/java/team9/ddang/family/repository/FamilyRepositoryTest.java
  src/test/java/team9/ddang/family/repository/WalkScheduleRepositoryTest.java
  src/test/java/team9/ddang/family/service/FamilyServiceImplTest.java
  src/test/java/team9/ddang/family/service/WalkScheduleServiceImplTest.java
  src/test/java/team9/ddang/member/service/ReportServiceImplTest.java
Labels: 🔨Refactor, 노관태

#89 fix: #88 WalkSchedule hard delete 적용
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/member/service/MemberServiceImpl.java
Labels: 🔥BugFix, 송경훈

#92 fix: #91 리밋 수정
  src/main/java/team9/ddang/chat/repository/ChatRepository.java
Labels: 🔥BugFix, 노관태

#94 feat: #93 객체 재조립
  src/main/java/team9/ddang/chat/service/ChatServiceImpl.java
Labels: ✨Feature, 노관태

#95 Feat#90 MemberController 테스트 코드 작성
  src/main/java/team9/ddang/member/controller/MemberController.java
  src/test/java/team9/ddang/member/controller/MemberControllerTest.java
Labels: 🧪Test, 송경훈

#98 Fix#97 mypage fix
  src/main/java/team9/ddang/member/service/response/MyPageResponse.java
Labels: 🔥BugFix, 송경훈

#96 [Feat/#84] 채팅 데이터 분리
  build.gradle
  src/main/java/team9/ddang/chat/repository/ChatRepository.java
  src/main/java/team9/ddang/chat/service/ChatAdminService.java
  src/main/java/team9/ddang/chat/service/ChatAdminServiceImpl.java
  src/main/java/team9/ddang/dog/service/DogService.java
  src/main/java/team9/ddang/global/config/batch/ChatBatchConfig.java
  src/main/java/team9/ddang/global/config/batch/ChatBatchScheduler.java
  src/main/java/team9/ddang/global/service/S3Service.java
Labels: ✨Feature, 노관태

#101 Refactor/#56 메인, 친구 테스트 코드 작성
  src/main/java/team9/ddang/global/config/websocket/StompHandler.java
  src/main/java/team9/ddang/member/repository/FriendRepository.java
  src/test/java/team9/ddang/ApiTestSupport.java
  src/test/java/team9/ddang/member/controller/FriendControllerTest.java
  src/test/java/team9/ddang/member/controller/MainControllerTest.java
  src/test/java/team9/ddang/member/repository/FriendRepositoryTest.java
  src/test/java/team9/ddang/member/service/FriendServiceImplTest.java
Labels: 🧪Test, 문재경

#102 [Feat/#100] 메인 응답 값 변경 및 산책 로직 수정
  src/main/java/team9/ddang/member/service/MainServiceImpl.java
  src/main/java/team9/ddang/member/service/response/MainResponse.java
  src/main/java/team9/ddang/walk/service/WalkLocationServiceImpl.java
Labels: ✨Feature, 문재경

#105 [Docs/#104] swagger error docs
  src/main/java/team9/ddang/chat/controller/ChatController.java
  src/main/java/team9/ddang/chat/controller/ChatRoomController.java
  src/main/java/team9/ddang/chat/controller/request/ChatRoomCreateRequest.java
  src/main/java/team9/ddang/chat/exception/ChatExceptionMessage.java
  src/main/java/team9/ddang/dog/controller/DogController.java
  src/main/java/team9/ddang/family/controller/FamilyController.java
  src/main/java/team9/ddang/family/controller/WalkScheduleController.java
  src/main/java/team9/ddang/family/exception/FamilyExceptionMessage.java
  src/main/java/team9/ddang/global/controller/WebSocketController.java
  src/main/java/team9/ddang/global/exception/WebSocketExceptionHandler.java
  src/main/java/team9/ddang/member/controller/ReportController.java
Labels: 📃 Docs, 노관태

#106 [Feat/#103] swagger error 명세 추가
  src/main/java/team9/ddang/global/controller/WebSocketWalkController.java
  src/main/java/team9/ddang/member/controller/FriendController.java
  src/main/java/team9/ddang/member/controller/MainController.java
  src/main/java/team9/ddang/member/service/FriendServiceImpl.java
  src/main/java/team9/ddang/member/service/MainServiceImpl.java
  src/main/java/team9/ddang/walk/controller/WalkController.java
  src/main/java/team9/ddang/walk/controller/WalkLogController.java
  src/main/java/team9/ddang/walk/controller/request/walk/DecisionWalkRequest.java
  src/main/java/team9/ddang/walk/exception/WalkExceptionMessage.java
Labels: 📃 Docs, 문재경

#109 [Feat/#108] family code dog
  src/main/java/team9/ddang/family/controller/FamilyController.java
  src/main/java/team9/ddang/family/service/FamilyService.java
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/family/service/response/FamilyDogResponse.java
  src/test/java/team9/ddang/family/service/FamilyServiceImplTest.java
Labels: ✨Feature, 📃 Docs, 노관태

#111 [Feat#107] member, notification swagger
  src/main/java/team9/ddang/member/controller/MemberController.java
  src/main/java/team9/ddang/member/controller/request/JoinRequest.java
  src/main/java/team9/ddang/member/controller/request/UpdateAddressRequest.java
  src/main/java/team9/ddang/member/controller/request/UpdateRequest.java
  src/main/java/team9/ddang/member/service/response/MemberResponse.java
  src/main/java/team9/ddang/member/service/response/MyPageResponse.java
  src/main/java/team9/ddang/member/service/response/UpdateInfoResponse.java
  src/main/java/team9/ddang/member/service/response/UpdateResponse.java
  src/main/java/team9/ddang/notification/controller/NotificationController.java
  src/main/java/team9/ddang/notification/controller/NotificationSettingsController.java
  src/main/java/team9/ddang/notification/controller/request/NotificationSettingsRequest.java
  src/main/java/team9/ddang/notification/service/response/NotificationResponse.java
  src/test/java/team9/ddang/member/controller/MemberControllerTest.java
Labels: 📃 Docs, 송경훈

#113 [Fix#112] 스웨거 명세에 Authorization 헤더 제거
  src/main/java/team9/ddang/member/controller/FriendController.java
  src/main/java/team9/ddang/member/controller/MainController.java
  src/main/java/team9/ddang/walk/controller/WalkLogController.java
Labels: 🔥BugFix, 송경훈

#116 [Fix#115] 알림 응답 수정
  src/main/java/team9/ddang/member/service/FriendServiceImpl.java
  src/main/java/team9/ddang/notification/scheduler/WalkScheduleNotificationScheduler.java
  src/main/java/team9/ddang/notification/scheduler/request/FamilyRoleMessageRequest.java
Labels: 🔨Refactor, 송경훈

#122 feat : #121 CORS 에러 해결
  src/main/java/team9/ddang/global/config/security/CorsConfig.java
  src/main/java/team9/ddang/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/team9/ddang/member/service/CookieService.java
Labels: 🔥BugFix, 문재경

#119 [feat/#118] API 수정
  src/main/java/team9/ddang/chat/controller/ChatRoomController.java
  src/main/java/team9/ddang/chat/service/ChatRoomServiceImpl.java
  src/main/java/team9/ddang/global/api/WebSocketResponse.java
  src/main/java/team9/ddang/global/config/websocket/StompHandler.java
  src/main/java/team9/ddang/global/controller/WebSocketController.java
Labels: ✨Feature, 노관태

#123 [Feat#114] MemberServiceImpl 테스트 코드 작성
  src/main/java/team9/ddang/notification/scheduler/WalkScheduleNotificationScheduler.java
  src/test/java/team9/ddang/member/service/MemberServiceImplTest.java
Labels: 🧪Test, 송경훈

#125 fix : #124 cors 엔드포인트 추가
  src/main/java/team9/ddang/global/config/security/CorsConfig.java
Labels: 🔥BugFix, 문재경

#127 docs: #126 README.md 추가
  README.md
  docs/Branch strategy and pull-request.md
  docs/Code Convention.md
Labels: 📃 Docs, 노관태
