Repository prgrms-web-devcourse-final-project/WEB1_1_DDang_BE, pull requests merged in 2024-11, with the labels that each got.

#5 [Feat/#3] websocket config 추가
  build.gradle
  src/main/java/team9/ddang/global/config/websocket/StompHandler.java
  src/main/java/team9/ddang/global/config/websocket/WebSocketConfig.java
Labels: ✨Feature, 문재경

#10 fix: #9 컬럼 중복 해결
  src/main/java/team9/ddang/member/entity/Friend.java
  src/main/java/team9/ddang/member/entity/FriendRequest.java
Labels: 🔥BugFix, 노관태

#16 [Feat/#12] 1대1 채팅 구현
  build.gradle
  src/main/java/team9/ddang/DDangApplication.java
  src/main/java/team9/ddang/chat/consumer/ChatConsumer.java
  src/main/java/team9/ddang/chat/controller/ChatController.java
  src/main/java/team9/ddang/chat/controller/ChatRoomController.java
  src/main/java/team9/ddang/chat/controller/request/ChatRequest.java
  src/main/java/team9/ddang/chat/controller/request/ChatRoomCreateRequest.java
  src/main/java/team9/ddang/chat/exception/ChatExceptionMessage.java
  src/main/java/team9/ddang/chat/producer/ChatProducer.java
  src/main/java/team9/ddang/chat/repository/ChatMemberRepository.java
  src/main/java/team9/ddang/chat/repository/ChatRepository.java
  src/main/java/team9/ddang/chat/repository/ChatRoomRepository.java
  src/main/java/team9/ddang/chat/service/ChatRoomService.java
  src/main/java/team9/ddang/chat/service/ChatRoomServiceImpl.java
  src/main/java/team9/ddang/chat/service/ChatService.java
  src/main/java/team9/ddang/chat/service/ChatServiceImpl.java
  src/main/java/team9/ddang/chat/service/KafkaDynamicListenerService.java
  src/main/java/team9/ddang/chat/service/WebSocketMessageService.java
  src/main/java/team9/ddang/chat/service/request/ChatServiceRequest.java
  src/main/java/team9/ddang/chat/service/response/ChatMemberInfo.java
  src/main/java/team9/ddang/chat/service/response/ChatResponse.java
  src/main/java/team9/ddang/chat/service/response/ChatRoomResponse.java
  src/main/java/team9/ddang/global/config/kafka/KafkaConsumerConfig.java
  src/main/java/team9/ddang/global/config/kafka/KafkaListenerInitializer.java
  src/main/java/team9/ddang/global/config/websocket/StompHandler.java
  src/main/java/team9/ddang/global/config/websocket/WebSocketConfig.java
  src/main/java/team9/ddang/member/entity/Member.java
  src/main/java/team9/ddang/member/repository/MemberRepository.java
  src/test/java/team9/ddang/IntegrationTestSupport.java
  src/test/java/team9/ddang/chat/repository/ChatRepositoryTest.java
Labels: ✨Feature, 노관태

#19 [Feat/#8] 산책 기능 구현
  build.gradle
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/global/api/ApiResponse.java
  src/main/java/team9/ddang/global/config/redis/RedisConfig.java
  src/main/java/team9/ddang/walk/controller/WalkController.java
  src/main/java/team9/ddang/walk/controller/WalkLocationController.java
  src/main/java/team9/ddang/walk/controller/request/CompleteWalkRequest.java
  src/main/java/team9/ddang/walk/controller/request/LocationRequest.java
  src/main/java/team9/ddang/walk/entity/Location.java
  src/main/java/team9/ddang/walk/entity/Position.java
  src/main/java/team9/ddang/walk/repository/LocationBulkRepository.java
  src/main/java/team9/ddang/walk/repository/LocationRepository.java
  src/main/java/team9/ddang/walk/repository/WalkDogRepository.java
  src/main/java/team9/ddang/walk/repository/WalkRepository.java
  src/main/java/team9/ddang/walk/service/RedisKey.java
  src/main/java/team9/ddang/walk/service/WalkLocationService.java
  src/main/java/team9/ddang/walk/service/WalkLocationServiceImpl.java
  src/main/java/team9/ddang/walk/service/WalkService.java
  src/main/java/team9/ddang/walk/service/WalkServiceImpl.java
  src/main/java/team9/ddang/walk/service/request/CompleteWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/request/LocationServiceRequest.java
  src/main/java/team9/ddang/walk/service/response/CompleteWalkAloneResponse.java
  src/main/java/team9/ddang/walk/service/response/MemberNearbyResponse.java
  src/main/java/team9/ddang/walk/util/LocationDistanceUtil.java
  src/main/java/team9/ddang/walk/util/WalkCalculator.java
Labels: ✨Feature, 문재경

#22 [Feat/#13] chat logic expansion
  src/main/java/team9/ddang/chat/consumer/ChatConsumer.java
  src/main/java/team9/ddang/chat/controller/ChatController.java
  src/main/java/team9/ddang/chat/controller/ChatRoomController.java
  src/main/java/team9/ddang/chat/controller/request/ChatReadRequest.java
  src/main/java/team9/ddang/chat/controller/request/ChatRoomCreateRequest.java
  src/main/java/team9/ddang/chat/entity/Chat.java
  src/main/java/team9/ddang/chat/entity/ChatMember.java
  src/main/java/team9/ddang/chat/entity/ChatRoom.java
  src/main/java/team9/ddang/chat/entity/IsRead.java
  src/main/java/team9/ddang/chat/event/MessageReadEvent.java
  src/main/java/team9/ddang/chat/producer/ChatProducer.java
  src/main/java/team9/ddang/chat/repository/ChatRepository.java
  src/main/java/team9/ddang/chat/service/ChatRoomService.java
  src/main/java/team9/ddang/chat/service/ChatRoomServiceImpl.java
  src/main/java/team9/ddang/chat/service/ChatService.java
  src/main/java/team9/ddang/chat/service/ChatServiceImpl.java
  src/main/java/team9/ddang/chat/service/KafkaDynamicListenerService.java
  src/main/java/team9/ddang/chat/service/request/ChatRoomCreateServiceRequest.java
  src/main/java/team9/ddang/chat/service/response/ChatResponse.java
  src/main/java/team9/ddang/chat/service/response/ChatRoomResponse.java
  src/main/java/team9/ddang/chat/service/response/PageableResponse.java
  src/main/java/team9/ddang/chat/service/response/SliceResponse.java
  src/main/java/team9/ddang/chat/service/response/SortResponse.java
  src/main/java/team9/ddang/global/config/websocket/StompHandler.java
  src/main/java/team9/ddang/global/config/websocket/WebSocketConfig.java
  src/main/java/team9/ddang/global/controller/WebSocketController.java
  src/main/java/team9/ddang/global/controller/response/WebSocketErrorResponse.java
  src/main/java/team9/ddang/global/exception/WebSocketExceptionHandler.java
Labels: ✨Feature, 📃 Docs, 노관태

#20 [Feat/#4] dog crud
  src/main/java/team9/ddang/dog/controller/DogController.java
  src/main/java/team9/ddang/dog/controller/request/CreateDogRequest.java
  src/main/java/team9/ddang/dog/controller/request/UpdateDogRequest.java
  src/main/java/team9/ddang/dog/entity/Dog.java
  src/main/java/team9/ddang/dog/repository/DogRepository.java
  src/main/java/team9/ddang/dog/service/DogService.java
  src/main/java/team9/ddang/dog/service/request/CreateDogServiceRequest.java
  src/main/java/team9/ddang/dog/service/request/UpdateDogServiceRequest.java
  src/main/java/team9/ddang/dog/service/response/CreateDogResponse.java
  src/main/java/team9/ddang/dog/service/response/GetDogResponse.java
Labels: ✨Feature, 장준우

#31 Feat#6 spring security + OAuth2 + JWT 인증 / 인가 구현
  build.gradle
  src/main/java/team9/ddang/DDangApplication.java
  src/main/java/team9/ddang/global/config/RedisConfig.java
  src/main/java/team9/ddang/global/config/SwaggerConfig.java
  src/main/java/team9/ddang/global/config/security/CorsConfig.java
  src/main/java/team9/ddang/global/config/security/SecurityConfig.java
  src/main/java/team9/ddang/member/controller/MemberController.java
  src/main/java/team9/ddang/member/controller/request/JoinRequest.java
  src/main/java/team9/ddang/member/entity/Member.java
  src/main/java/team9/ddang/member/entity/Role.java
  src/main/java/team9/ddang/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/team9/ddang/member/jwt/service/JwtService.java
  src/main/java/team9/ddang/member/oauth2/CustomOAuth2User.java
  src/main/java/team9/ddang/member/oauth2/OAuth2Attributes.java
  src/main/java/team9/ddang/member/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/team9/ddang/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/team9/ddang/member/oauth2/service/CustomOAuth2UserService.java
  src/main/java/team9/ddang/member/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/team9/ddang/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/team9/ddang/member/oauth2/userinfo/NaverOAuth2UserInfo.java
  src/main/java/team9/ddang/member/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/team9/ddang/member/repository/MemberRepository.java
  src/main/java/team9/ddang/member/service/CookieService.java
  src/main/java/team9/ddang/member/service/MemberService.java
  src/main/java/team9/ddang/member/service/MemberServiceImpl.java
  src/main/java/team9/ddang/member/service/request/JoinServiceRequest.java
  src/main/java/team9/ddang/member/service/response/MemberResponse.java
  src/test/java/team9/ddang/ApiTestSupport.java
  src/test/java/team9/ddang/member/controller/MemberControllerTest.java
  src/test/java/team9/ddang/member/jwt/JwtServiceTest.java
Labels: ✨Feature, 🔥BugFix, 🔨Refactor, 송경훈

#34 Fix33# DDangApplication 에러 수정
  src/main/java/team9/ddang/DDangApplication.java
  src/main/java/team9/ddang/global/config/redis/RedisConfig.java
Labels: 🔥BugFix

#35 [Feat/#21] 강번따 기능 구현
  src/main/java/team9/ddang/dog/entity/Dog.java
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/global/api/ApiResponse.java
  src/main/java/team9/ddang/global/api/WebSocketResponse.java
  src/main/java/team9/ddang/global/controller/WebSocketWalkController.java
  src/main/java/team9/ddang/global/exception/GlobalExceptionHandler.java
  src/main/java/team9/ddang/global/service/RedisService.java
  src/main/java/team9/ddang/member/entity/WalkWithMember.java
  src/main/java/team9/ddang/member/repository/MemberRepository.java
  src/main/java/team9/ddang/member/repository/WalkWithMemberRepository.java
  src/main/java/team9/ddang/walk/controller/WalkController.java
  src/main/java/team9/ddang/walk/controller/WalkLocationController.java
  src/main/java/team9/ddang/walk/controller/request/DecisionWalkRequest.java
  src/main/java/team9/ddang/walk/controller/request/ProposalWalkRequest.java
  src/main/java/team9/ddang/walk/controller/request/StartWalkRequest.java
  src/main/java/team9/ddang/walk/service/RedisKey.java
  src/main/java/team9/ddang/walk/service/WalkLocationService.java
  src/main/java/team9/ddang/walk/service/WalkLocationServiceImpl.java
  src/main/java/team9/ddang/walk/service/WalkService.java
  src/main/java/team9/ddang/walk/service/WalkServiceImpl.java
  src/main/java/team9/ddang/walk/service/request/DecisionWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/request/ProposalWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/request/StartWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/response/CompleteWalkAloneResponse.java
  src/main/java/team9/ddang/walk/service/response/CompleteWalkResponse.java
  src/main/java/team9/ddang/walk/service/response/MemberNearbyInfo.java
  src/main/java/team9/ddang/walk/service/response/MemberNearbyResponse.java
  src/main/java/team9/ddang/walk/service/response/ProposalWalkResponse.java
  src/main/java/team9/ddang/walk/service/response/WalkWithDogInfo.java
  src/main/java/team9/ddang/walk/service/response/WalkWithResponse.java
  src/main/java/team9/ddang/walk/util/DateCalculator.java
Labels: ✨Feature, 문재경

#37 Feat#32 마이페이지 조회 기능
  src/main/java/team9/ddang/member/controller/MemberController.java
  src/main/java/team9/ddang/member/entity/Member.java
  src/main/java/team9/ddang/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/team9/ddang/member/repository/WalkWithMemberRepository.java
  src/main/java/team9/ddang/member/service/MemberService.java
  src/main/java/team9/ddang/member/service/MemberServiceImpl.java
  src/main/java/team9/ddang/member/service/response/MemberResponse.java
  src/main/java/team9/ddang/member/service/response/MyPageResponse.java
  src/main/java/team9/ddang/walk/repository/WalkRepository.java
  src/test/java/team9/ddang/chat/repository/ChatRepositoryTest.java
  src/test/java/team9/ddang/member/controller/MemberControllerTest.java
Labels: ✨Feature, 🔨Refactor, 송경훈

#38 [Feat/#25] feat family basic
  build.gradle
  src/main/java/team9/ddang/dog/repository/DogRepository.java
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/family/controller/FamilyController.java
  src/main/java/team9/ddang/family/controller/request/FamilyCreateRequest.java
  src/main/java/team9/ddang/family/controller/request/FamilyJoinRequest.java
  src/main/java/team9/ddang/family/entity/Family.java
  src/main/java/team9/ddang/family/exception/FamilyExceptionMessage.java
  src/main/java/team9/ddang/family/repository/FamilyRepository.java
  src/main/java/team9/ddang/family/service/FamilyService.java
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/family/service/request/FamilyCreateServiceRequest.java
  src/main/java/team9/ddang/family/service/response/FamilyDetailResponse.java
  src/main/java/team9/ddang/family/service/response/FamilyResponse.java
  src/main/java/team9/ddang/family/service/response/InviteCodeResponse.java
  src/main/java/team9/ddang/global/api/ApiResponse.java
  src/main/java/team9/ddang/member/entity/Member.java
  src/main/java/team9/ddang/member/repository/MemberRepository.java
  src/test/java/team9/ddang/ApiTestSupport.java
  src/test/java/team9/ddang/family/controller/FamilyControllerTest.java
  src/test/java/team9/ddang/family/repository/FamilyRepositoryTest.java
  src/test/java/team9/ddang/family/service/FamilyServiceImplTest.java
Labels: ✨Feature, 노관태

#39 [Feat/#36] 산책 나머지 기능 정리
  src/main/java/team9/ddang/global/aop/AuthenticationContext.java
  src/main/java/team9/ddang/global/aop/ExtractEmail.java
  src/main/java/team9/ddang/global/aop/JwtAuthenticationAspect.java
  src/main/java/team9/ddang/global/exception/AuthenticationException.java
  src/main/java/team9/ddang/global/exception/CustomException.java
  src/main/java/team9/ddang/global/exception/ExceptionMessage.java
  src/main/java/team9/ddang/global/exception/GlobalExceptionHandler.java
  src/main/java/team9/ddang/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/team9/ddang/member/jwt/service/JwtService.java
  src/main/java/team9/ddang/walk/controller/WalkController.java
  src/main/java/team9/ddang/walk/controller/WalkLocationController.java
  src/main/java/team9/ddang/walk/exception/WalkExceptionMessage.java
  src/main/java/team9/ddang/walk/service/WalkLocationService.java
  src/main/java/team9/ddang/walk/service/WalkLocationServiceImpl.java
  src/main/java/team9/ddang/walk/service/WalkService.java
  src/main/java/team9/ddang/walk/service/WalkServiceImpl.java
Labels: ✨Feature, 문재경

#40 [Feat/#29] walk schedule
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/family/controller/WalkScheduleController.java
  src/main/java/team9/ddang/family/controller/request/WalkScheduleCreateRequest.java
  src/main/java/team9/ddang/family/entity/WalkSchedule.java
  src/main/java/team9/ddang/family/exception/FamilyExceptionMessage.java
  src/main/java/team9/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/family/service/WalkScheduleService.java
  src/main/java/team9/ddang/family/service/WalkScheduleServiceImpl.java
  src/main/java/team9/ddang/family/service/request/WalkScheduleCreateServiceRequest.java
  src/main/java/team9/ddang/family/service/response/WalkScheduleResponse.java
  src/test/java/team9/ddang/family/repository/WalkScheduleRepositoryTest.java
  src/test/java/team9/ddang/family/service/WalkScheduleServiceImplTest.java
Labels: ✨Feature, 노관태

#41 [Feat/#24 친구 기능 개발]
  src/main/java/team9/ddang/member/controller/FriendController.java
  src/main/java/team9/ddang/member/controller/request/AddFriendRequest.java
  src/main/java/team9/ddang/member/entity/Friend.java
  src/main/java/team9/ddang/member/entity/FriendRequest.java
  src/main/java/team9/ddang/member/repository/FriendRepository.java
  src/main/java/team9/ddang/member/repository/FriendRequestRepository.java
  src/main/java/team9/ddang/member/service/FriendService.java
  src/main/java/team9/ddang/member/service/FriendServiceImpl.java
  src/main/java/team9/ddang/member/service/request/AddFriendServiceRequest.java
  src/main/java/team9/ddang/member/service/response/FriendListResponse.java
  src/main/java/team9/ddang/member/service/response/FriendResponse.java
  src/test/java/team9/ddang/ApiTestSupport.java
  src/test/java/team9/ddang/member/controller/FriendControllerTest.java
Labels: ✨Feature, 문재경

#43 [Feat/#30] user report
  src/main/java/team9/ddang/family/controller/WalkScheduleController.java
  src/main/java/team9/ddang/family/controller/request/WalkScheduleCreateRequest.java
  src/main/java/team9/ddang/family/service/response/WalkScheduleResponse.java
  src/main/java/team9/ddang/member/controller/ReportController.java
  src/main/java/team9/ddang/member/controller/request/ReportRequest.java
  src/main/java/team9/ddang/member/entity/Report.java
  src/main/java/team9/ddang/member/exception/MemberExceptionMessage.java
  src/main/java/team9/ddang/member/repository/ReportRepository.java
  src/main/java/team9/ddang/member/service/ReportService.java
  src/main/java/team9/ddang/member/service/ReportServiceImpl.java
  src/main/java/team9/ddang/member/service/request/ReportServiceRequest.java
  src/test/java/team9/ddang/member/service/ReportServiceImplTest.java
Labels: ✨Feature, 📃 Docs, 노관태

#45 [Feat/#28] 댕댕로그
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/global/controller/WebSocketWalkController.java
  src/main/java/team9/ddang/member/repository/MemberRepository.java
  src/main/java/team9/ddang/walk/controller/WalkController.java
  src/main/java/team9/ddang/walk/controller/WalkLocationController.java
  src/main/java/team9/ddang/walk/controller/WalkLogController.java
  src/main/java/team9/ddang/walk/controller/request/log/GetLogByDateRequest.java
  src/main/java/team9/ddang/walk/controller/request/walk/CompleteWalkRequest.java
  src/main/java/team9/ddang/walk/controller/request/walk/DecisionWalkRequest.java
  src/main/java/team9/ddang/walk/controller/request/walk/ProposalWalkRequest.java
  src/main/java/team9/ddang/walk/controller/request/walk/StartWalkRequest.java
  src/main/java/team9/ddang/walk/repository/LocationRepository.java
  src/main/java/team9/ddang/walk/repository/WalkDogRepository.java
  src/main/java/team9/ddang/walk/repository/WalkRepository.java
  src/main/java/team9/ddang/walk/service/WalkLocationService.java
  src/main/java/team9/ddang/walk/service/WalkLocationServiceImpl.java
  src/main/java/team9/ddang/walk/service/WalkLogService.java
  src/main/java/team9/ddang/walk/service/WalkLogServiceImpl.java
  src/main/java/team9/ddang/walk/service/WalkService.java
  src/main/java/team9/ddang/walk/service/WalkServiceImpl.java
  src/main/java/team9/ddang/walk/service/request/log/GetLogByDateServiceRequest.java
  src/main/java/team9/ddang/walk/service/request/walk/CompleteWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/request/walk/DecisionWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/request/walk/ProposalWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/request/walk/StartWalkServiceRequest.java
  src/main/java/team9/ddang/walk/service/response/TimeDuration.java
  src/main/java/team9/ddang/walk/service/response/log/WalkLogByFamilyResponse.java
  src/main/java/team9/ddang/walk/service/response/log/WalkLogResponse.java
  src/main/java/team9/ddang/walk/service/response/log/WalkStaticsResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/CompleteWalkResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/MemberNearbyInfo.java
  src/main/java/team9/ddang/walk/service/response/walk/MemberNearbyResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/ProposalWalkResponse.java
  src/main/java/team9/ddang/walk/service/response/walk/WalkWithDogInfo.java
  src/main/java/team9/ddang/walk/service/response/walk/WalkWithResponse.java
  src/main/java/team9/ddang/walk/util/DateCalculator.java
Labels: ✨Feature, 문재경

#49 [Feat/#27] 메인 화면 API
  src/main/java/team9/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/team9/ddang/member/controller/MainController.java
  src/main/java/team9/ddang/member/service/MainService.java
  src/main/java/team9/ddang/member/service/MainServiceImpl.java
  src/main/java/team9/ddang/member/service/response/MainResponse.java
  src/main/java/team9/ddang/walk/repository/WalkDogRepository.java
Labels: ✨Feature, 문재경

#48 Feat/#26 dog crud enhancement
  src/main/java/team9/ddang/dog/controller/DogController.java
  src/main/java/team9/ddang/dog/controller/request/UpdateDogRequest.java
  src/main/java/team9/ddang/dog/entity/Dog.java
  src/main/java/team9/ddang/dog/entity/MemberDog.java
  src/main/java/team9/ddang/dog/repository/DogRepository.java
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/dog/service/DogService.java
Labels: ✨Feature

#52 Feat#51 mypage 추가 요구사항 반영
  src/main/java/team9/ddang/dog/repository/DogRepository.java
  src/main/java/team9/ddang/dog/repository/MemberDogRepository.java
  src/main/java/team9/ddang/member/controller/MemberController.java
  src/main/java/team9/ddang/member/service/MemberServiceImpl.java
  src/main/java/team9/ddang/member/service/response/MyPageResponse.java
  src/test/java/team9/ddang/member/controller/MemberControllerTest.java
Labels: ✨Feature, 송경훈

#53 [refactor : #50] 부족했던 명세 추가
  src/main/java/team9/ddang/global/controller/WebSocketWalkController.java
  src/main/java/team9/ddang/member/service/response/MainResponse.java
  src/main/java/team9/ddang/walk/controller/WalkController.java
  src/main/java/team9/ddang/walk/controller/request/walk/CompleteWalkRequest.java
  src/main/java/team9/ddang/walk/service/response/walk/ProposalWalkResponse.java
  src/main/java/team9/ddang/walk/util/WalkCalculator.java
Labels: 🔨Refactor, 문재경

#55 Feat#54 패밀리댕에 강아지 정보 반영 및 강이지 Swagger 작성
  src/main/java/team9/ddang/dog/controller/DogController.java
  src/main/java/team9/ddang/family/service/FamilyServiceImpl.java
  src/main/java/team9/ddang/family/service/response/FamilyDetailResponse.java
  src/main/java/team9/ddang/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/team9/ddang/walk/repository/WalkRepository.java
Labels: ✨Feature, 송경훈
